### ISSUE TITLE
Issue when installing the EDM RDS plugin

### ISSUE THREAD

**Issue by drums114** [FalconChristmas/fpp-edmrds#14]
Installing plugin fpp-edmrds
Cloning into 'fpp-edmrds'...
Running fpp_install.sh script for fpp-edmrds
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
pigpio is already the newest version (1.79-1+rpt1).
python3-pigpio is already the newest version (1.79-1+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
Traceback (most recent call last):
  File "/home/fpp/media/plugins/fpp-edmrds/rds-song.py", line 24, in <module>
    s = bb_I2C.I2C(pi, 23, 24, 600)
  File "/home/fpp/media/plugins/fpp-edmrds/bb_I2C.py", line 216, in __init__
    pi.run_script(self.sid, [0, SCL, SDA, self.dly])
  File "/usr/lib/python3/dist-packages/pigpio.py", line 4373, in run_script
    ext.extend(struct.pack("I", p))
struct.error: required argument is not an integer
{"Status":"Error","Message":"Could not properly install plugin"}

**Comment by computergeek1507** [comment]
can you try updating, 3499d78a2c685ae2b844954bc4466b820f415919 should fix it

**Comment by drums114** [comment]
It seems like it updates but there is no text on my car radios.  I tried to 2 different cars.  It seems like it updates but I don't see the text on the radio and I made sure the mp3 tags were filled it.

**Comment by jefft0825** [comment]
![Screenshot 2023-10-07 203432](https://github.com/FalconChristmas/fpp-edmrds/assets/39816390/6d24fafd-b986-4942-a7d0-341bbd5b0478)
I am seeing some weird characters this year on the RDS part - has anything changed on this?

**Comment by drums114** [comment]
Hi Scott is it still pin 23 and 24 on the latest PI?
